name: Dep gcc

on:
  push:
    paths:
      - '.github/workflows/deps-gcc.yaml'
      - 'deps/gcc/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        version:
          - '11.5.0'
          - '12.4.0'
          - '13.4.0'
          - '14.3.0'
          - '15.1.0'
        enable_2stage:
          - 'true'
          - 'false'
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: deps/gcc
          file: deps/gcc/Dockerfile
          push: true
          build-args: |
            GCC_VERSION=${{ matrix.version }}
            ENABLE_2STAGE=${{ matrix.enable_2stage }}
          tags: curoky/devspace:deps-gcc-${{ matrix.version }}-2stage_${{ matrix.enable_2stage }}

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
